FORMAT: 1A

# Test

# Resource [/resource]
## Create Resource [POST]

+ request A

        {
            "hello": "world"
        }

+ response 200

        a

+ request B

        b

+ response 200

        b
